### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by chaoscreater** [OnigiriFest/free-games-epicstore#1]
Chromedriver opens and takes me to the login page, but doesn't do anything. I've set up the config properly.

```
Traceback (most recent call last):
  File "C:\Users\blah\Downloads\Others\free-games-epicstore-master\get_free_shit.py", line 3, in <module>
    login()
  File "C:\Users\blah\Downloads\Others\free-games-epicstore-master\epicgames.py", line 27, in login
    email_element = driver.find_element_by_name('usernameOrEmail')
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="usernameOrEmail"]"}
  (Session info: chrome=83.0.4103.97)
```

**Comment by facundopanizza** [comment]
I'm sorry i had a lot of exams in the school at that time!, I'm going to see whats going on probably Epic games updated the webpage, if you want you can use this project https://github.com/Revadike/epicgames-freebies-claimer.
